apiVersion: v1
kind: ServiceAccount
metadata:
  name : sa-test
  namespace: default


---  ## 토큰 생성
apiVersion: v1
kind: Secret
type: kubernets.io/service-account-token
metadata:
  name: sa-token
  namespace: default
  annotations:
    kubernets.io/service-account.name: "sa-test"
