---
apiVersion: v1
kind: Pod
metadata:
  name: dep-mysql
  labels:
    app: mysql

spec:
  containers:
  - name: mysql
    image: mysql:5.7
    imagePullPolicy: Never
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: test1234!
    - name: MYSQL_DATABASE
      value: wordpress
    - name: MYSQL_ROOT_HOST
      value: "%"


---
apiVersion: v1
kind: Pod
metadata:
  name: word-rep
  labels:
    app: word

spec:
  containers:
  - name: word
    image: wordpress
    env:
    - name: WORDPRESS_DB_HOST
      value: 10.38.0.1:3306
    - name: WORDPRESS_DB_NAME
      value: wordpress
    - name: WORDPRESS_DB_USER
      value: root
    - name: WORDPRESS_DB_PASSWORD
      value: test1234!
    ports:
    - containerPort: 80
