apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    env: test

spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/web/"
