apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  labels:
    env: test

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
